[package]
name = "models"
version = "0.1.0"
edition = "2018"

[dependencies]
uuid = { version = "0.8.1", features = ["v4", "serde"] }
serde = { version = "1.0.53", features = ["derive"] }
serde_derive = "1.0.53"